services:
  - type: web
    name: my-application
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SESSION
        value: "RGNK~qJgA4mNP"
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString
